---
- name: Make sure unofficial Docker components are uninstalled
  apt:
    pkg:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
  tags:
    - docker

- name: Install Docker via convenience script
  shell: |
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
  args:
    executable: /bin/bash
  tags:
    - docker

- name: Enable IPv6 for Docker daemon by default
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  tags:
    - docker

- name: Ensure Docker service is enabled
  service:
    name: docker
    enabled: yes
  tags:
    - docker

- name: Ensure 'dc' shortcut is in .bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    state: present
    line: 'alias dc="docker compose"'
  tags:
    - docker

- name: Ensure 'dsp' shortcut is in .bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    state: present
    line: 'alias dsp="docker system prune -af && docker network prune -f && docker volume prune -f"'
  tags:
    - docker
